config/routes.rb
Rails.application.routes.draw do
  #ルートパス設定完了（4/3 18:00）
  root :to => 'homes#top'
  # resources:books
  # get '/books' => 'books#new'
  post '/books' => 'books#create'
  get '/books' => 'books#index'
  get '/books/:id' => 'books#show', as: 'book'
  get '/books/:id/edit' => 'books#edit', as: 'edit_book'
  patch '/books/:id' => 'books#update', as: 'book_update'
  delete '/books/:id' => 'books#destroy', as: 'book_destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 validates:title,presence:true
 validates:body,presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notion] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render:index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notion] = "Book was successfully updated."
     redirect_to book_path(@book.id)
    else
      @books = Book.all
      render:edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notion] = "Book was successfully destroyed."
    redirect_to '/books'
  end

  private
  def book_params
    #
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1 class="edit-header">Editing Book</h1>

<% if @book.errors.any? %>
 <div class="errors-section">
  <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
   <ul>
    <% @book.errors.full_messages.each do |messages| %>
    <li><%= messages %></li>
    <% end %>
   </ul> 
 </div>  
<% end %>

<%= form_with model: @book, url:book_update_path(@book.id), method: :patch do |edit_book| %>

<% if !@book.errors.any? %>
 <div class="field">
  <div class="field-header">
   <label>Title</label>
  </div>
  <div class="field-text">
   <%= edit_book.text_field:title %>
  </div>
 </div>
  <div class="field">
  <div class="field-header">
   <label>Body</label>
  </div>
  <div class="field-text">
   <%= edit_book.text_area:body %>
  </div>
 </div>
 <% else %>
 <div class="field">
  <div class="field-error-header">
   <label>Title</label>
  </div>
  <div class="field-error-text">
   <%= edit_book.text_field:title %>
  </div>
 </div>
 <div class="field">
  <div class="field-error-header">
   <label>Body</label>
  </div>
  <div class="field-error-text">
   <%= edit_book.text_area:body %>
  </div>
 </div>
<% end %>
 <div class="edit-submit">
  <%= edit_book.submit 'Update Book' %>
 </div>

<%= link_to "Show", book_path(@book.id) %> |
<%= link_to "Back", '/books' %>

<% end %>

app/views/books/index.html.erb
<!--投稿削除完了の際のフラッシュメッセージ表示-->
<p class="flash-text"><%= flash[:notion] %></p>

<!--投稿一覧機能-->
<h1 class="index-header">Books</h1>


<table>
  <thead>
  <tr>
    <th>Title</th><th>Body</th><th colspan="3"></th>
  </tr>
  </thead>

   <% @books.each do |book| %>

    <tr>
     <td><%= book.title %></td>
     <td><%= book.body %></td>
     <td><%= link_to "Show", book_path(book.id) %></td>
     <td><%= link_to "Edit", edit_book_path(book.id) %></td>
     <td><%= link_to "Destroy", book_destroy_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>
   <% end %>

</table>


<!--新規投稿機能-->
<h2 class="create-header">New books</h2>

<% if @book.errors.any? %>
 <div class="errors-section">
  <h2><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
  <ul>
   <% @book.errors.full_messages.each do |messages| %>
   <li><%= messages %></li>
   <% end %>
  </ul>
 </div>
<% end %>

<%= form_with model: @book do |f| %>
<% if !@book.errors.any? %>
<div class="field">
 <div class="field-header">
  <label>Title</label>
 </div>
 <div class="field-text">
   <%= f.text_field:title %>
 </div>
</div>
 <div class="field">
  <div class="field-header">
   <label>Body</label>
  </div>
  <div class="field-text">
   <%= f.text_area:body %>
  </div>
</div>
 <% else %>
 <div class="field">
 <div class="field-error-header">
  <label>Title</label>
 </div>
 <div class="field-error-text">
   <%= f.text_field:title %>
 </div>
</div>

 <div class="field">
  <div class="field-error-header">
   <label>Body</label>
  </div>
  <div class="field-error-text">
   <%= f.text_area:body %>
  </div>
</div>
<% end %>
 <div class="submit">
  <%= f.submit 'Create Book' %>
 </div>

<% end %>

app/views/books/show.html.erb
<!--投稿・編集完了の際のフラッシュメッセージ表示-->
<p class="flash-text"><%= flash[:notion] %></p>

<p><strong>Title:</strong>
  <%= @book.title %>
</p>
<p><strong>Body:</strong>
  <%= @book.body %>
</p>

<%= link_to "Edit", edit_book_path(@book) %> |
<%= link_to "Back", '/books' %>

app/views/homes/top.html.erb
<h1>
   ようこそ
   <strong>Bookers</strong>
   へ！
</h1>

 <p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
 <p>印象を共有し交換することができます</p>
 <p><%= link_to 'start',  '/books' %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>